apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-app-dev1
  namespace: argocd
spec:
  destination:
    namespace: dev1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: springboot-app/
    repoURL: https://github.com/JithuPaul24/syncer_cicd_flows.git
    targetRevision: dev1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true