apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-app-staging
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: springboot-app/
    repoURL: https://github.com/JithuPaul24/syncer_cicd_flows.git
    targetRevision: staging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true