apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  serviceAccountName: build-bot
  triggers:
    - name: github-trigger
      bindings:
      - ref: github-push-trigger-binding
      template:
        ref: github-push-trigger-template
